# Generated by Django 5.1.4 on 2024-12-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('moves', models.TextField()),
            ],
            options={
                'db_table': 'Traps',
            },
        ),
    ]
