# Generated by Django 5.1.4 on 2024-12-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opening',
            table='Openings',
        ),
    ]
