# Generated by Django 5.1.4 on 2024-12-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_alter_opening_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('moves', models.TextField()),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='openings.opening')),
            ],
            options={
                'db_table': 'Variations',
            },
        ),
    ]
