name: Build and deploy Python app to Azure Web App - cestquoilouverture

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Django collectstatic
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      # Inject secrets into environment variables
      - name: Set environment variables
        run: |
          echo "DBUSER=${{ secrets.DBUSER }}" >> $GITHUB_ENV
          echo "DBPASSWORD=${{ secrets.DBPASSWORD }}" >> $GITHUB_ENV

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x venv/**\*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Install dependencies for deployment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set environment variables for deployment
        run: |
          echo "DBUSER=${{ secrets.DBUSER }}" >> $GITHUB_ENV
          echo "DBPASSWORD=${{ secrets.DBPASSWORD }}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'cestquoilouverture'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
