name: Build and deploy Python app to Azure Web App - cestquoilouverture

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Replace passwords with secrets
        run: |
          sed -i "s/DB_USER_/${{ secrets.DB_USER }}/g" cestquoilouverture/settings.py
          sed -i "s/DB_PASSWORD_/${{ secrets.DB_PASSWORD }}/g" cestquoilouverture/settings.py

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cestquoilouverture'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3280D8060C594471BBBC8FDCBC693576 }}
